### ISSUE TITLE
Add code coverage (tarpaulin)

### ISSUE THREAD

**Issue by nbigaouette** [xoac/rust-azure-pipelines#12]
I've added code coverage using tarpaulin in my project. Running it is not as slow as I expected. Azure Pipelines are quite fast!

It was also quite simple, I mainly had to find how to run Docker containers.

Here are the lines:
https://github.com/nbigaouette/pycors/blob/d9d8d54ffbf0401f551ba668ce57ee0b9dcd15ea/azure-pipelines.yml#L88-L106

Note that a `containers` section to `resources` is needed too:
https://github.com/nbigaouette/pycors/blob/d9d8d54ffbf0401f551ba668ce57ee0b9dcd15ea/azure-pipelines.yml#L14-L17

Here's another project that uses tarpaulin inside docker in Azure Pipelines:
https://github.com/tsukuyomi-rs/tsukuyomi/blob/11da727b3a498d3e905985c765f21836b7589ba7/azure-pipelines.yml#L109-L127

**Comment by xoac** [comment]
I will look this when Windows and macOS releases will work
