### ISSUE TITLE
Considering changing tar.gz release for .zip?

### ISSUE THREAD

**Issue by nbigaouette** [xoac/rust-azure-pipelines#13]
The GitHub release template uses a gzip-compressed tarball (`tar.gz`) for its archive.

While perfect for macOS and Linux, it is annoying to use for Windows as there isn't any program that support that format in a vanilla install of Windows. It can, though, unpack zip archives just fine.

Could the GitHub release archive format be changed to `.zip` instead? The change would simply be to use `archiveType: 'zip'`. Or maybe an option could be given?

Thanks!

**Comment by xoac** [comment]
I agree `zip` can be default and option for changing this would be nice ;)
