### ISSUE TITLE
Consider tagging master / making release

### ISSUE THREAD

**Issue by nbigaouette** [xoac/rust-azure-pipelines#15]
One can depend on this repository to provide templates for the CI config. For example the current config example uses `master` as the version to use for the template:
https://github.com/xoac/rust-azure-pipelines/blob/b9b5936166462d6070afaa212195851cecd5a372/azure-pipelines.yml#L12

This can be problematic for reproducibility. If the templates repo changes then the CI config of other repos depending on this one could fail at a future time even though nothing in them changed. To prevent this problem, using a reference that does not change in time (like the name of a branch) should be done instead.

According to the Azure Pipelines documentation on templates, one cannot specify a commit id to pin the dependency on a template:

> If you want to use a particular, fixed version of the template, be sure to pin to a ref. Refs are either branches (`refs/heads/<name>`) or tags (`refs/tags/<name>`). If you want to pin a specific commit, first create a tag pointing to that commit, then pin to that tag.

Reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

So according to the doc, it's either the name of a branch (which evolves over time) or a tag. Since depending on a moving target is problematic, only git tags remains as the secure way.

As such, could you create and push a tag to create a release for the latest version in master? This way I can fix my dependency on it and be sure to have a reliable CI.

Thanks a lot!!

**Comment by xoac** [comment]
The tag is the must. I will release 0.0.2 soon. Nobody should use master in production since I can break it accidentally.

**Comment by xoac** [comment]
Released tag [v0.0.2](https://github.com/xoac/rust-azure-pipelines/tree/v0.0.2)

**Comment by xoac** [comment]
Btw Thanks you for your effort for this project - it helps a lot!
