### ISSUE TITLE
Hardcoded project name in github releases

### ISSUE THREAD

**Issue by chmln** [xoac/rust-azure-pipelines#16]
Hello @xoac 

It looks like the `rust-azure-pipelines` name for assets in github releases is hard-coded. See https://github.com/xoac/rust-azure-pipelines/blob/master/ci/github-release.yml#L50 for example.

Would it be more appropriate to use `Build.Repository.Name` instead? If so, I can make a quick pull request. 

Thanks for the work you did on this. I'm using it for https://github.com/chmln/sd and everything else works perfectly.

**Comment by xoac** [comment]
I will try fix it tomorrow
