### ISSUE TITLE
Support releases for macOS

### ISSUE THREAD

**Issue by xoac** [xoac/rust-azure-pipelines#9]

**Comment by nbigaouette** [comment]
Was about to open an issue for that! :D Thanks

**Comment by nbigaouette** [comment]
Also, I wanted to ask... It seems the releases are built using `cross` to cross-compile for the different platforms.

Wouldn't it be better if those releases were built on native platforms instead? Azure Pipelines _do_ support those...

**Comment by nbigaouette** [comment]
Windows build seems broken too. See for example: https://dev.azure.com/nbigaouette/pycors/_build/results?buildId=39

**Comment by xoac** [comment]
@nbigaouette  It's not broken -- it's [not supported](https://github.com/rust-embedded/cross#supported-targets). But I think I can support this by agent exactly the same as for macOS

**Comment by nbigaouette** [comment]
I've looked at how the gh release template and the build template worked to create a hard coded release job. See it here: https://github.com/nbigaouette/pycors/blob/4801f1b6b8a45e5ccd8082b514d8b0367ef99e9d/azure-pipelines.yml#L130-L199

[This release](https://github.com/nbigaouette/pycors/releases/tag/v0.1.10.2) was crafted using this.

The only issue I see is that it [doesn't build a linux musl static binary](https://github.com/nbigaouette/pycors/issues/64), only a `linux-gnu` one.

This approach doesn't use `cross` though as your template does.

**Comment by xoac** [comment]
I will use cross to build targets. I will just support additionally Windows and macOS. Sorry so long to implement that. I will try do it today evening but it can potentially take more than one day.

**Comment by nbigaouette** [comment]
No worries! I'm grateful about your work which saved me a lot of time, so thank you!

**Comment by xoac** [comment]
@nbigaouette Do u use macOS? if yes can u confirm this [binary](https://github.com/xoac/rust-azure-pipelines/releases/tag/v0.0.2-alpha.4) print `hello world`?

**Comment by nbigaouette** [comment]
Yes, hello world works fine.

```
> ./rust-azure-pipelines
Hello, world!
```
